### ISSUE TITLE
eventhough not using typescript, gulp build stumbles on typescriptServices.js

### ISSUE THREAD

**Issue by sallespro** [dustinspecker/generator-ng-poly#125]
```
node_modules/typescript/bin/typescriptServices.js:25313
});
^
SyntaxError: Unexpected token }
    at Module._compile (module.js:439:25)

```
and short after

```
gulp build

Error: ENOENT, no such file or directory '/home/mel/node/poly/sparkyo/node_modules/typescript/bin/lib.d.ts'
    at Object.fs.openSync (fs.js:439:18)
    at Object.fs.readFileSync (fs.js:290:15)```

**Comment by dustinspecker** [comment]
Looks like npm failed to install typescript. Run `npm install typescript` and that should fix this issue.

The Gulpfile supports all languages, which is why this is occurring. You may remove `typescript` and `gulp-typescript` from `package.json` and remove its usage in the Gulp files.

**Comment by sallespro** [comment]
thanks dustin. 
i am troubled by `Gulpfile.js` dependencies.

```
$ gulp dev
[19:43:19] Using gulpfile ~/node/poly/sparkyo/Gulpfile.js
[19:43:19] Starting 'clean'...
[19:43:19] Starting 'lint'...
[19:43:20] Starting 'staticAnalysis'...
[19:43:21] Finished 'clean' after 1.99 s
[19:43:21] Starting 'markup'...
[19:43:22] 'markup' errored after 639 ms
[19:43:22] Error: Cannot find module 'acorn/util/walk'
```

**Comment by dustinspecker** [comment]
Closing this as #133 will address this.
