### ISSUE TITLE
On Typescript project got "path must be a string"

### ISSUE THREAD

**Issue by Ajacs** [dustinspecker/generator-ng-poly#146]
Today i create a project (typescript) , and when i try to run "gulp" i get the following error:

```javascript
AssertionError: path must be a string
    at Module.require (module.js:362:3)
    at require (module.js:380:17)
    at requireFn (/home/adderly/wix2mart/wix2mart/node_modules/gulp-load-plugins/index.js:37:14)
    at Object.defineProperty.get (/home/adderly/wix2mart/wix2mart/node_modules/gulp-load-plugins/index.js:59:18)
    at Object.<anonymous> (/home/adderly/wix2mart/wix2mart/Gulpfile.js:52:21)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

**Comment by dustinspecker** [comment]
I think this is an npm install failure. Looks like it's either gulp-load-plugins or gulp-typescript. Try running `npm install gulp-load-plugins gulp-typescript`.

**Comment by g0r1v3r4** [comment]
When running the following command for e2e with protractor - I got:
````
$ gulp webdriverUpdate
AssertionError: path must be a string
    at Module.require (module.js:362:3)
    at require (module.js:380:17)
    at requireFn (/home/gorivera/ModernDev/coqui-dev-portal/moderndev/node_modules/gulp-load-plugins/index.js:37:14)
    at Object.defineProperty.get (/home/gorivera/ModernDev/coqui-dev-portal/moderndev/node_modules/gulp-load-plugins/index.js:59:18)
    at Object.<anonymous> (/home/gorivera/ModernDev/coqui-dev-portal/moderndev/Gulpfile.js:51:21)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
````

After installing gulp-load-plugins- when I re-ran the `gulp webdriverUpdate` and got the error:

````
Error: Cannot find module 'gulp-typescript'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at requireFn (/home/gorivera/ModernDev/coqui-dev-portal/moderndev/node_modules/gulp-load-plugins/index.js:40:16)
    at Object.defineProperty.get (/home/gorivera/ModernDev/coqui-dev-portal/moderndev/node_modules/gulp-load-plugins/index.js:65:18)
    at Object.<anonymous> (/home/gorivera/ModernDev/coqui-dev-portal/moderndev/Gulpfile.js:51:21)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
````

So, I went ahead and installed the `gulp-typescript` package. Now I was able to successfully install the Selenium server standalone and chromedriver.

````
$ gulp webdriverUpdate
[23:25:35] Using gulpfile ~/ModernDev/coqui-dev-portal/moderndev/Gulpfile.js
[23:25:35] Starting 'webdriverUpdate'...
Updating selenium standalone
downloading https://selenium-release.storage.googleapis.com/2.45/selenium-server-standalone-2.45.0.jar...
Updating chromedriver
downloading https://chromedriver.storage.googleapis.com/2.14/chromedriver_linux64.zip...
chromedriver_2.14.zip downloaded to /home/gorivera/ModernDev/coqui-dev-portal/moderndev/node_modules/gulp-protractor/node_modules/protractor/selenium/chromedriver_2.14.zip
selenium-server-standalone-2.45.0.jar downloaded to /home/gorivera/ModernDev/coqui-dev-portal/moderndev/node_modules/gulp-protractor/node_modules/protractor/selenium/selenium-server-standalone-2.45.0.jar
[23:25:43] Finished 'webdriverUpdate' after 8.07 s
````

All is good now - but why is there a dependency on `gulp-typescript`? - I only ask because my project does not use typescript - just curious - but the above solution should work - thanks Dustin.

**Comment by dustinspecker** [comment]
Glad to hear that fixed it - really strange you both had failures on the same module. Thanks for sharing. The reasoning is discussed in #133 and will be changed in the future.
