### ISSUE TITLE
gulp unitTest not running tests

### ISSUE THREAD

**Issue by d-rep** [dustinspecker/generator-ng-poly#162]
Sometimes `gulp unitTest` will run tests correctly...

```
[09:06:33] Using gulpfile ~/ng-poly-sample/Gulpfile.js
[09:06:33] Starting 'lint'...
[09:06:35] Starting 'clean'...
[09:06:35] Starting 'staticAnalysis'...
[09:06:35] Starting 'clean:test'...
[09:06:35] Finished 'staticAnalysis' after 62 ms
[09:06:35] Finished 'clean:test' after 62 ms
[09:06:35] Finished 'clean' after 238 ms
[09:06:35] Starting 'markup'...
[09:06:36] Starting 'styles'...
[09:06:38] Starting 'bowerAssets'...
[09:06:38] Starting 'images'...
[09:06:40] Starting 'fonts'...
[09:06:40] Finished 'images' after 2.04 s
[09:06:40] Finished 'fonts' after 10 ms
[09:06:40] Finished 'lint' after 7.39 s
[09:06:40] Starting 'analyze'...
[09:06:40] Finished 'analyze' after 5.58 μs
[09:06:40] Starting 'buildTests'...
[09:06:42] Finished 'styles' after 6.15 s
[09:06:42] Finished 'markup' after 6.61 s
[09:06:42] Starting 'scripts'...
[09:06:43] Finished 'buildTests' after 2.41 s
[09:06:43] Finished 'bowerAssets' after 4.81 s
[09:06:43] Finished 'scripts' after 968 ms
[09:06:43] Starting 'inject'...
[09:06:43] gulp-inject 13 files into index.html.
[09:06:43] Finished 'inject' after 245 ms
[09:06:43] Starting 'bowerCopy'...
[09:06:43] Finished 'bowerCopy' after 57 ms
[09:06:43] Starting 'bowerInject'...
[09:06:44] Finished 'bowerInject' after 311 ms
[09:06:44] Starting 'copyTemplates'...
[09:06:44] Finished 'copyTemplates' after 43 ms
[09:06:44] Starting 'deleteTemplates'...
[09:06:44] Finished 'deleteTemplates' after 8.19 μs
[09:06:44] Starting 'build'...
[09:06:44] Finished 'build' after 13 μs
[09:06:44] Starting 'karmaFiles'...
[09:06:44] Finished 'karmaFiles' after 51 ms
[09:06:44] Starting 'unitTest'...
INFO [karma]: Karma v0.12.31 server started at http://localhost:9876/
INFO [launcher]: Starting browser PhantomJS
INFO [PhantomJS 1.9.8 (Mac OS X)]: Connected on socket GeNLTFDteiwmfrKf71vp with id 92554582

PhantomJS 1.9.8 (Mac OS X) failed specs:
  HomeCtrl > should have a list with items
	TypeError: 'undefined' is not an object (evaluating 'ctrl.lists.items.length')
	    at /Users/drew/ng-poly-sample/build/test/app/home/home-controller_test.js:18


  HomeCtrl > should remove item from list
	TypeError: 'undefined' is not an object (evaluating 'ctrl.lists.items[1]')
	    at /Users/drew/ng-poly-sample/build/test/app/home/home-controller_test.js:26



[09:06:49] Finished 'unitTest' after 5.17 s
```

Other times `gulp unitTest` will simply stop after the *bowerAssets* task completes.  I can see the *scripts* task starting but not finishing.

```
[09:42:17] Using gulpfile ~/ng-poly-sample/Gulpfile.js
[09:42:17] Starting 'lint'...
[09:42:19] Starting 'clean'...
[09:42:20] Starting 'staticAnalysis'...
[09:42:20] Starting 'clean:test'...
[09:42:20] Finished 'staticAnalysis' after 64 ms
[09:42:20] Finished 'clean' after 232 ms
[09:42:20] Starting 'markup'...
[09:42:20] Starting 'styles'...
[09:42:22] Starting 'bowerAssets'...
[09:42:23] Starting 'images'...
[09:42:25] Starting 'fonts'...
[09:42:25] Finished 'clean:test' after 4.97 s
[09:42:25] Finished 'images' after 1.92 s
[09:42:25] Finished 'fonts' after 10 ms
[09:42:25] Finished 'markup' after 5.07 s
[09:42:25] Finished 'lint' after 7.31 s
[09:42:25] Starting 'analyze'...
[09:42:25] Finished 'analyze' after 12 μs
[09:42:25] Starting 'scripts'...
[09:42:27] Starting 'buildTests'...
[09:42:27] Finished 'styles' after 6.76 s
[09:42:27] Finished 'buildTests' after 276 ms
[09:42:27] Finished 'bowerAssets' after 4.78 s
```

In the generator, I chose ES6 and Material Design.  This is on Mac OS X.

**Comment by d-rep** [comment]
One workaround is to remove Typescript and Coffeescript support.  My ./gulp/build.js looks like the following and now `gulp unitTest` seems to run consistently.

```
      .pipe(es6Filter)
      .pipe($.babel())
      .pipe($.rename(function (filePath) {
        filePath.extname = '.js';
      }))
      .pipe(es6Filter.restore())
      //.pipe(typescriptFilter)
      //.pipe($.typescript(config.tsProject))
      //.pipe(typescriptFilter.restore())
      //.pipe(coffeeFilter)
      //.pipe($.coffee())
      //.pipe(coffeeFilter.restore())
```

**Comment by pr80ik** [comment]
I can confirm that removing the typescript and coffee script support made the unitTest target work for me. However I don't know what the root cause is; I have seen it work without any change on some computers.

Following is the change I made:
```
--- a/gulp/test.js
+++ b/gulp/test.js
@@ -13,9 +13,7 @@ module.exports = function (gulp, $, config) {
   });

   gulp.task('buildTests', ['lint', 'clean:test'], function () {
-    var typescriptFilter = $.filter('**/*.ts')
-      , coffeeFilter = $.filter('**/*.coffee')
-      , es6Filter = $.filter('**/*.es6')
+    var es6Filter = $.filter('**/*.es6')
       , jsFilter = $.filter('**/*.js');

     return gulp.src([config.unitTestFiles])
@@ -25,12 +23,6 @@ module.exports = function (gulp, $, config) {
         filePath.extname = '.js';
       }))
       .pipe(es6Filter.restore())
-      .pipe(typescriptFilter)
-      .pipe($.typescript(config.tsProject))
-      .pipe(typescriptFilter.restore())
-      .pipe(coffeeFilter)
-      .pipe($.coffee())
-      .pipe(coffeeFilter.restore())
       .pipe(jsFilter)
       .pipe(gulp.dest(config.buildUnitTestsDir))
       .pipe(jsFilter.restore());
```

**Comment by erezak** [comment]
I can confirm the same.
The workaround won't work for me, because I am using TypeScript.

The task always fails on buildTests (see below)

Interestingly, running buildTests on its own does work. So I created a new task (ut) that doesn't depend on anything. It requires me to run buildTests and then ut.
@dustinspecker - any comment?


Fail log:

[17:01:47] Finished 'bowerAssets' after 3.48 s
[17:01:47] Finished 'styles' after 6.28 s
[17:01:47] Finished 'markup' after 6.92 s
[17:01:48] ESLint found no problems in 1 file
[17:01:48] ESLint found no problems in 1 file
[17:01:48] ESLint found no problems in 1 file
[17:01:48] ESLint found no problems in 1 file
[17:01:48] ESLint found no problems in 1 file
[17:01:48] ESLint found no problems in 1 file
[17:01:48] ESLint found no problems in 1 file
[17:01:48] ESLint found no problems in 1 file
[17:01:48] ESLint found no problems in 1 file
[17:01:48] ESLint found no problems in 1 file
[17:01:48] Finished 'lint' after 10 s
[17:01:48] Starting 'analyze'...
[17:01:48] Finished 'analyze' after 8.84 μs
[17:01:48] Starting 'scripts'...
[17:01:51] Starting 'buildTests'...
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: stream.push() after EOF
  at readableAddChunk (_stream_readable.js:149:15)
  at CompileOutputStream.Readable.push (_stream_readable.js:126:10)
  at Output.emit (C:\c\wrk\selfie\node_modules\gulp-typescript\release\output.js:161:28)
  at Output.addOrMergeFile (C:\c\wrk\selfie\node_modules\gulp-typescript\release\output.js:78:26)
  at Output.write (C:\c\wrk\selfie\node_modules\gulp-typescript\release\output.js:36:14)
  at ProjectCompiler.inputDone (C:\c\wrk\selfie\node_modules\gulp-typescript\release\compiler.js:65:33)
  at CompileStream.end (C:\c\wrk\selfie\node_modules\gulp-typescript\release\main.js:52:31)
  at DestroyableTransform.onend (C:\c\wrk\selfie\node_modules\gulp-filter\node_modules\through2\node_modules\readable-stream\lib\_st
ream_readable.js:523:10)
  at DestroyableTransform.g (events.js:199:16)
  at DestroyableTransform.emit (events.js:129:20)
  at C:\c\wrk\selfie\node_modules\gulp-filter\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:965:16
  at process._tickCallback (node.js:355:11)

**Comment by dustinspecker** [comment]
Hmmm. I did an npm update gulp-typescript and then the task worked correctly for me. Could one of you please verify updating gulp-typescript to 2.7.5 works for you? If so, I'll bump the dep version and hopefully that fixes the flakiness.

**Comment by erezak** [comment]
No luck, sorry - gulp-typescript was already at 2.7.5.
I -f installed it and the results are the same. (node version v0.12.4)

**Comment by erezak** [comment]
The issue is definitely with the buildTests task, but only when it's being run in the context of another task. For example - running watch and changing a file causes the exact same error.

**Comment by dustinspecker** [comment]
Interesting. I tried unitTest while watching: it was fine on 0.12.2. I upgraded to 0.12.4 and now I'm getting the same error as you.

I tried installing gulp-typescript@2.6.0 and that version works correctly for me on Node 0.12.4. I'll dig into that and see what changed between 2.6.0 and 2.7.5.

**Comment by erezak** [comment]
**Yes**, nice catch. downgrading gulp-typescript did the trick. Thank you.

**Comment by dustinspecker** [comment]
34d9b79b7207f6db20316ef6508021ab5f8e224a Locking gulp-typescript to 2.6.0 for the time being.

**Comment by dustinspecker** [comment]
So, playing around with this working on adding TypeScript@1.5.0 support.

Seems to be an issue if both the TypeScript source AND tests create declaration files. Since, most likely people aren't creating `d.ts` files in tests, we can create two separate typescript projects from Gulp's perspective.

In `gulpfile.js`, change

```javascript
config.tsProject = $.typescript.createProject({
  declarationFiles: true,
  noExternalResolve: false
});
```

to

```javascript
config.tsSrcProject = $.typescript.createProject({
  declarationFiles: true,
  noExternalResolve: false
});
```

and in the same file create:

```javascript
config.tsTestProject = $.typescript.createProject({
  declarationFiles: false,
  noExternalResolve: false
});
```

In `gulp/build.js` change references from `config.tsProject` to `config.tsSrcProject` and in `gulp/test.js` change references from `config.tsProject` to `config.tsTestProject`.

I'll get this released in a bit. Not sure why this is a problem or how to even go about submitting a PR to gulp-typescript.

**Comment by egeland** [comment]
With those manual changes to the gulp scripts, I have it working on gulp-typescript `v2.9.2`, too. :)
