### ISSUE TITLE
Unexpected token 

### ISSUE THREAD

**Issue by jackygrahamez** [dustinspecker/generator-ng-poly#177]
I am trying to run the project for the first time after I did I a build
I ran ```gulp```
and got this error...
```
[12:59:20] Starting 'components'...

events.js:85
      throw er; // Unhandled 'error' event
            ^
SyntaxError: /Users/jgs/Projects/Personal/ng-poly/polytest/bower_components/polymer/polymer-micro.html: Unexpected token (1:1)
> 1 | <!--
    |  ^
  2 | @license
  3 | Copyright (c) 2014 The Polymer Project Authors. All rights reserved.
  4 | This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
    at Parser.pp.raise (/Users/jgs/Projects/Personal/ng-poly/polytest/node_modules/gulp-babel/node_modules/babel-core/lib/acorn/src/location.js:80:13)
    at Parser.pp.unexpected (/Users/jgs/Projects/Personal/ng-poly/polytest/node_modules/gulp-babel/node_modules/babel-core/lib/acorn/src/parseutil.js:95:8)
    at Parser.pp.jsx_parseIdentifier (/Users/jgs/Projects/Personal/ng-poly/polytest/node_modules/gulp-babel/node_modules/babel-core/node_modules/acorn-jsx/inject.js:191:12)
    at Parser.pp.jsx_parseNamespacedName (/Users/jgs/Projects/Personal/ng-poly/polytest/node_modules/gulp-babel/node_modules/babel-core/node_modules/acorn-jsx/inject.js:200:21)
    at Parser.pp.jsx_parseElementName (/Users/jgs/Projects/Personal/ng-poly/polytest/node_modules/gulp-babel/node_modules/babel-core/node_modules/acorn-jsx/inject.js:213:21)
    at Parser.pp.jsx_parseOpeningElementAt (/Users/jgs/Projects/Personal/ng-poly/polytest/node_modules/gulp-babel/node_modules/babel-core/node_modules/acorn-jsx/inject.js:291:22)
    at Parser.pp.jsx_parseElementAt (/Users/jgs/Projects/Personal/ng-poly/polytest/node_modules/gulp-babel/node_modules/babel-core/node_modules/acorn-jsx/inject.js:314:31)
```

**Comment by dustinspecker** [comment]
Oops, forgot to filter in that task. The changes in `gulp/build.js` from this commit https://github.com/dustinspecker/generator-ng-poly/commit/e36a9c553e9e9458be9e38905accf14fb07444d8 should fix the problem. Sorry about the inconvenience and thanks for bringing this up.
