### ISSUE TITLE
4 unit tests fail

### ISSUE THREAD

**Issue by serddmitry** [dustinspecker/generator-ng-poly#229]
I've cloned the generator to customize templates, and 0.11.2 build fails on my machine.
I'm using node v.5.0.0 x64, Win 7.

```
  4 failing

  1) App Utils getAppDir should return app dir:
     Error: Cannot find module 'awesome-project\build.config.js'
      at Function.mock [as _requireMock] (c:\my\temp\generator-ng-poly\node_modules\a_mock\partialMock\simple\newPartialMock.js:34:23)
      at Function.loadHook [as _load] (c:\my\temp\generator-ng-poly\node_modules\a_mock\expectRequire.js:14:14)
      at Proxyquire._require (c:\my\temp\generator-ng-poly\node_modules\proxyquire\lib\proxyquire.js:164:19)
      at getFileFromRoot$ (c:\my\temp\generator-ng-poly\generators\utils\app.js:9:1817)
      at tryCatch (c:\my\temp\generator-ng-poly\node_modules\regenerator\runtime.js:61:40)
      at GeneratorFunctionPrototype.invoke [as _invoke] (c:\my\temp\generator-ng-poly\node_modules\regenerator\runtime.js:328:22)
      at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (c:\my\temp\generator-ng-poly\node_modules\regenerator\runtime.js:94:21)

  2) App Utils getFileFromRoot should return file JS/JSON:
     Error: Cannot find module 'awesome-project\file.js'
      at Function.mock [as _requireMock] (c:\my\temp\generator-ng-poly\node_modules\a_mock\partialMock\simple\newPartialMock.js:34:23)
      at Function.loadHook [as _load] (c:\my\temp\generator-ng-poly\node_modules\a_mock\expectRequire.js:14:14)
      at Proxyquire._require (c:\my\temp\generator-ng-poly\node_modules\proxyquire\lib\proxyquire.js:164:19)
      at Object.getFileFromRoot$ (c:\my\temp\generator-ng-poly\generators\utils\app.js:9:1817)
      at tryCatch (c:\my\temp\generator-ng-poly\node_modules\regenerator\runtime.js:61:40)
      at GeneratorFunctionPrototype.invoke [as _invoke] (c:\my\temp\generator-ng-poly\node_modules\regenerator\runtime.js:328:22)
      at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (c:\my\temp\generator-ng-poly\node_modules\regenerator\runtime.js:94:21)

  3) App Utils getUnitTestDir should return unit test dir:
     Error: Cannot find module 'awesome-project\build.config.js'
      at Function.mock [as _requireMock] (c:\my\temp\generator-ng-poly\node_modules\a_mock\partialMock\simple\newPartialMock.js:34:23)
      at Function.loadHook [as _load] (c:\my\temp\generator-ng-poly\node_modules\a_mock\expectRequire.js:14:14)
      at Proxyquire._require (c:\my\temp\generator-ng-poly\node_modules\proxyquire\lib\proxyquire.js:164:19)
      at getFileFromRoot$ (c:\my\temp\generator-ng-poly\generators\utils\app.js:9:1817)
      at tryCatch (c:\my\temp\generator-ng-poly\node_modules\regenerator\runtime.js:61:40)
      at GeneratorFunctionPrototype.invoke [as _invoke] (c:\my\temp\generator-ng-poly\node_modules\regenerator\runtime.js:328:22)
      at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (c:\my\temp\generator-ng-poly\node_modules\regenerator\runtime.js:94:21)

  4) Module Utils moduleFilter should check for x-module name only on child directory:

      AssertionError: expected [ Array(2) ] to deeply equal [ Array(3) ]
      + expected - actual

         {
           "name": "abc"
           "value": "abc"
         }
      +  {
      +    "name": "nested/nest"
      +    "value": "nested/nest"
      +  }
       ]

      at Context._callee10$ (test-utils-module.js:241:26)
      at tryCatch (c:\my\temp\generator-ng-poly\node_modules\regenerator\runtime.js:61:40)
      at GeneratorFunctionPrototype.invoke [as _invoke] (c:\my\temp\generator-ng-poly\node_modules\regenerator\runtime.js:328:22)
      at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (c:\my\temp\generator-ng-poly\node_modules\regenerator\runtime.js:94:21)
      at GeneratorFunctionPrototype.invoke (c:\my\temp\generator-ng-poly\node_modules\regenerator\runtime.js:136:37)
      at bound (domain.js:280:14)
      at GeneratorFunctionPrototype.runBound (domain.js:293:12)
      at run (c:\my\temp\generator-ng-poly\node_modules\core-js\modules\es6.promise.js:104:47)
      at c:\my\temp\generator-ng-poly\node_modules\core-js\modules\es6.promise.js:115:28
      at flush (c:\my\temp\generator-ng-poly\node_modules\core-js\modules\$.microtask.js:19:5)




events.js:141
      throw er; // Unhandled 'error' event
      ^
 Error: 4 tests failed.
npm ERR! Test failed.  See above for more details.

```

**Comment by dustinspecker** [comment]
Ooops. I will try to get those fixed later tonight. Thank you for pointing that out.
