### ISSUE TITLE
yo ng-poly fails with 'babel-polyfill' module error after update

### ISSUE THREAD

**Issue by jdiver** [dustinspecker/generator-ng-poly#230]
After updating to the latest version of the ng-poly generator, I'm getting the following error when trying to use it (any "yo ng-poly" command):

```
module.js:339
    throw err;
    ^

Error: Cannot find module 'babel-polyfill'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/generator-ng-poly/generators/app/index.js:3:1)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
```

I've tried uninstalling and reinstalling, but it results in the same error.

**Comment by dustinspecker** [comment]
Sorry about that. Huge oversight on my part. I'll release the fix in just a few minutes (my Travis CI is pretty backlogged right now).

**Comment by jdiver** [comment]
Thanks for the super quick fix - all good now! :+1:
