### ISSUE TITLE
yo ng-poly:module core

### ISSUE THREAD

**Issue by fmatuszewski** [dustinspecker/generator-ng-poly#235]
TypeError: Arguments to path.join must be strings
    at Object.posix.join (path.js:488:13)
    at getFileFromRoot$ (/usr/local/lib/node_modules/generator-ng-poly/generators/utils/app.js:34:40)
    at tryCatch (/usr/local/lib/node_modules/generator-ng-poly/node_modules/babel-regenerator-runtime/runtime.js:61:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/generator-ng-poly/node_modules/babel-regenerator-runtime/runtime.js:329:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/generator-ng-poly/node_modules/babel-regenerator-runtime/runtime.js:94:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/generator-ng-poly/node_modules/babel-regenerator-runtime/runtime.js:136:37)
    at run (/usr/local/lib/node_modules/generator-ng-poly/node_modules/core-js/modules/es6.promise.js:104:47)
    at /usr/local/lib/node_modules/generator-ng-poly/node_modules/core-js/modules/es6.promise.js:115:28
    at flush (/usr/local/lib/node_modules/generator-ng-poly/node_modules/core-js/modules/$.microtask.js:19:5)
    at process._tickCallback (node.js:355:11)
TypeError: Arguments to path.join must be strings
    at Object.posix.join (path.js:488:13)
    at getFileFromRoot$ (/usr/local/lib/node_modules/generator-ng-poly/generators/utils/app.js:34:40)
    at tryCatch (/usr/local/lib/node_modules/generator-ng-poly/node_modules/babel-regenerator-runtime/runtime.js:61:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/generator-ng-poly/node_modules/babel-regenerator-runtime/runtime.js:329:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/generator-ng-poly/node_modules/babel-regenerator-runtime/runtime.js:94:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/generator-ng-poly/node_modules/babel-regenerator-runtime/runtime.js:136:37)
    at run (/usr/local/lib/node_modules/generator-ng-poly/node_modules/core-js/modules/es6.promise.js:104:47)
    at /usr/local/lib/node_modules/generator-ng-poly/node_modules/core-js/modules/es6.promise.js:115:28
    at flush (/usr/local/lib/node_modules/generator-ng-poly/node_modules/core-js/modules/$.microtask.js:19:5)
    at process._tickCallback (node.js:355:11)

**Comment by dustinspecker** [comment]
Hey, thanks for reporting this. Looks similar to #231 and I haven't been able to reproduce it, yet.

Could you provide some more info please?

ng-poly version
Node version
npm version
Is this a new project or an existing project? If existing, what version of ng-poly was used to scaffold it?

**Comment by dustinspecker** [comment]
I believe this has been fixed, if not please feel free to re-open.
