### ISSUE TITLE
Module selection doesn't work

### ISSUE THREAD

**Issue by Isigiel** [dustinspecker/generator-ng-poly#242]
When reating a new thing, the module selection simply deosn't work, arrow keys have no impact at all.
Also when supplying the module via a flag I get this error:
    
    TypeError: Cannot read property 'indexOf' of undefined
    at Object.findModuleFile$ (C:\Users\Lukas\AppData\Roaming\npm\node_modules\generator-ng-poly\generators\utils\module.js:228:25)
    at tryCatch (C:\Users\Lukas\AppData\Roaming\npm\node_modules\generator-ng-poly\node_modules\babel-regenerator-runtime\runtime.js:61:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\Lukas\AppData\Roaming\npm\node_modules\generator-ng-poly\node_modules\babel-regenerator-runtime\runtime.js:329:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\Users\Lukas\AppData\Roaming\npm\node_modules\generator-ng-poly\node_modules\babel-regenerator-runtime\runtime.js:94:21)
    at GeneratorFunctionPrototype.invoke (C:\Users\Lukas\AppData\Roaming\npm\node_modules\generator-ng-poly\node_modules\babel-regenerator-runtime\runtime.js:136:37)
    at run (C:\Users\Lukas\AppData\Roaming\npm\node_modules\generator-ng-poly\node_modules\core-js\modules\es6.promise.js:104:47)
    at C:\Users\Lukas\AppData\Roaming\npm\node_modules\generator-ng-poly\node_modules\core-js\modules\es6.promise.js:115:28
    at flush (C:\Users\Lukas\AppData\Roaming\npm\node_modules\generator-ng-poly\node_modules\core-js\modules\$.microtask.js:19:5)
    at doNTCallback0 (node.js:419:9)
    at process._tickCallback (node.js:348:13)
    TypeError: Cannot read property 'indexOf' of undefined
    at Object.findModuleFile$ (C:\Users\Lukas\AppData\Roaming\npm\node_modules\generator-ng-poly\generators\utils\module.js:228:25)
    at tryCatch (C:\Users\Lukas\AppData\Roaming\npm\node_modules\generator-ng-poly\node_modules\babel-regenerator-runtime\runtime.js:61:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\Lukas\AppData\Roaming\npm\node_modules\generator-ng-poly\node_modules\babel-regenerator-runtime\runtime.js:329:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\Users\Lukas\AppData\Roaming\npm\node_modules\generator-ng-poly\node_modules\babel-regenerator-runtime\runtime.js:94:21)
    at GeneratorFunctionPrototype.invoke (C:\Users\Lukas\AppData\Roaming\npm\node_modules\generator-ng-poly\node_modules\babel-regenerator-runtime\runtime.js:136:37)
    at run (C:\Users\Lukas\AppData\Roaming\npm\node_modules\generator-ng-poly\node_modules\core-js\modules\es6.promise.js:104:47)
    at C:\Users\Lukas\AppData\Roaming\npm\node_modules\generator-ng-poly\node_modules\core-js\modules\es6.promise.js:115:28
    at flush (C:\Users\Lukas\AppData\Roaming\npm\node_modules\generator-ng-poly\node_modules\core-js\modules\$.microtask.js:19:5)
    at doNTCallback0 (node.js:419:9)
    at process._tickCallback (node.js:348:13)

I'm using typescript and have not really added anything, or changed anything on the initial template
Creating stuff on the mein app module does work though

EDIT:
_I have tried to use the generator without ts, but get the same problems. Apart from that I really admire the work you did on this generator and would love to use it._

**Comment by dustinspecker** [comment]
Thank you for the issue. I've been trying to track this down recently and have been unable to reproduce it. I was hoping Typescript was the issue.

Interesting that it happens on a freshly scaffolded project.

Which version of npm and Node are you using? Could you share the generated `build.config.js` and `.yo-rc.json` files?

**Comment by Isigiel** [comment]
npm -v: 3.5.2
node -v v4.2.3
http://ghost.iamtrue.net/paste/wy6xv (the files you requested)

Thanks for looking into that so quick

**Comment by dustinspecker** [comment]
Ugh, those versions work fine for me with your settings. Thanks for providing that info.

Hmm. Are you using any special characters in your module names? Not renaming any files, right? 

I'm running out of ideas.

I'm setting up a Windows VM at the moment, but I don't think it's Windows specific as the other reported issues are on Unix.

Thank you for the help; it's greatly appreciated.

**Comment by Isigiel** [comment]
Runnig out of ideas sounds bad ;(
I threw up a new  app to give all details possible: http://i.imgur.com/LNYaKKl.png
When creating a new route the selection of modules doesn't work, after some arrow-hitting the app name appears http://i.imgur.com/jm7X25e.png
It turns out, the slection is actually done, just not displayed.
Lastly this is the already posted output of a supplied module http://i.imgur.com/6JTketn.png

**Comment by dustinspecker** [comment]
Whoa, your second picture is weird. How is ng-poly making a module named `app/home killer`? That's definitely messed up.

Also, the module argument doesn't take the app prefix. So, would `--module=home` work?

**Comment by Isigiel** [comment]
**--module= home** works just fine, maybe add that to the readme, I took the name from the list the generator provides, I can imagine many people doing that

Another thing I noticed, was, some libs, (node-sass) seem to be very old, maybe they need some :heart:

**Comment by javierquevedo** [comment]
I get the exact same error when trying to create a new module :(
On the contrary, I can create a directive for instance, and there I am able to select the module without any issues.

**Comment by dustinspecker** [comment]
I believe this has been fixed, if not please feel free to re-open.
