### ISSUE TITLE
'unitTest' errored in a newly created ng-poly project

### ISSUE THREAD

**Issue by samdeesh** [dustinspecker/generator-ng-poly#272]
Please find the below logs for details

smenia$ gulp unitTest
[17:34:41] Using gulpfile ~/Documents/yo/sammy/Gulpfile.js
[17:34:41] Starting 'lint'...
[17:35:19] Starting 'clean'...
[17:35:19] Starting 'staticAnalysis'...
[17:35:19] Starting 'clean:test'...
[17:35:19] Finished 'clean:test' after 35 ms
[17:35:29] ESLint found no problems in 1 file
[17:35:30] Finished 'clean' after 11 s
[17:35:30] Starting 'markup'...
[17:35:30] Starting 'styles'...
[17:35:51] Starting 'bowerAssets'...
[17:35:53] Starting 'images'...
[17:36:06] Starting 'favicon'...
[17:36:06] Starting 'fonts'...
[17:36:06] ESLint found no problems in 1 file
[17:36:06] Finished 'lint' after 1.42 min
[17:36:06] Starting 'buildTests'...
[17:36:06] Finished 'images' after 13 s
[17:36:06] Finished 'favicon' after 291 ms
[17:36:06] Finished 'fonts' after 290 ms
[17:36:06] Finished 'styles' after 36 s
[17:36:06] Finished 'buildTests' after 16 ms
[17:36:06] Finished 'markup' after 37 s
[17:36:08] Finished 'staticAnalysis' after 49 s
[17:36:08] Starting 'analyze'...
[17:36:08] Finished 'analyze' after 13 μs
[17:36:08] Starting 'scripts'...
[17:36:22] Finished 'scripts' after 14 s
[17:36:22] Starting 'inject'...
[17:36:24] gulp-inject 4 files into index.html.
[17:36:24] Finished 'bowerAssets' after 33 s
[17:36:24] Finished 'inject' after 1.93 s
[17:36:24] Starting 'bowerCopy'...
[17:36:25] Finished 'bowerCopy' after 212 ms
[17:36:25] Starting 'bowerInject'...
[17:36:28] Finished 'bowerInject' after 3.29 s
[17:36:28] Starting 'copyTemplates'...
[17:36:28] Finished 'copyTemplates' after 376 ms
[17:36:28] Starting 'deleteTemplates'...
[17:36:28] Finished 'deleteTemplates' after 16 μs
[17:36:28] Starting 'build'...
[17:36:28] Finished 'build' after 8.33 μs
[17:36:28] Starting 'karmaFiles'...
[17:36:28] Finished 'karmaFiles' after 94 ms
[17:36:28] Starting 'unitTest'...
22 03 2016 17:36:50.303:WARN [watcher]: Pattern "/Users/smenia/Documents/yo/sammy/node_modules/karma-babel-preprocessor/node_modules/babel-core/browser-polyfill.js" does not match any file.
22 03 2016 17:36:50.527:INFO [karma]: Karma v0.13.22 server started at http://localhost:9876/
22 03 2016 17:36:50.697:INFO [launcher]: Starting browser PhantomJS
22 03 2016 17:36:56.988:INFO [PhantomJS 1.9.8 (Mac OS X 0.0.0)]: Connected on socket /#w8iNMc5L3ackIllKAAAA with id 61893374

[17:36:57] 'unitTest' errored after 29 s
[17:36:57] Error: 1
    at formatError (/usr/local/lib/node_modules/gulp/bin/gulp.js:169:10)
    at Gulp.<anonymous> (/usr/local/lib/node_modules/gulp/bin/gulp.js:195:15)
    at emitOne (events.js:77:13)
    at Gulp.emit (events.js:169:7)
    at Gulp.Orchestrator._emitTaskDone (/Users/smenia/Documents/yo/sammy/node_modules/gulp/node_modules/orchestrator/index.js:264:8)
    at /Users/smenia/Documents/yo/sammy/node_modules/gulp/node_modules/orchestrator/index.js:275:23
    at finish (/Users/smenia/Documents/yo/sammy/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:21:8)
    at cb (/Users/smenia/Documents/yo/sammy/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:29:3)
    at removeAllListeners (/Users/smenia/Documents/yo/sammy/node_modules/karma/lib/server.js:336:7)
    at Server.<anonymous> (/Users/smenia/Documents/yo/sammy/node_modules/karma/lib/server.js:347:9)
    at Server.g (events.js:260:16)
    at emitNone (events.js:72:20)
    at Server.emit (events.js:166:7)
    at emitCloseNT (net.js:1521:8)
    at doNTCallback1 (node.js:439:9)
    at process._tickCallback (node.js:361:17)

**Comment by dustinspecker** [comment]
Did npm or Bower happen to fail during the initial scaffold? I've seen issues with that in the past. If either one fails during install then ng-poly fails to scaffold the `home` module. Please let me know if you have a `home` module.

Sorry for the inconvenience.

**Comment by dustinspecker** [comment]
Closing due to inactivity. Please feel free to reopen later.

**Comment by surajplobal** [comment]
@dustinspecker  I am facing the same issue. home module is present in my newly created project.
