### ISSUE TITLE
Initial setup succeeds but can not generate anything on OS X 10.11.4

### ISSUE THREAD

**Issue by cyang6** [dustinspecker/generator-ng-poly#321]
Here's my node env on OS X 10.11.4 : node v4.4.4 npm v2.15.6
After app setup, I run this command in project folder: yo ng-poly:directive my-directive
It runs forever with no output
I got error message after terminating the process:
I checked my folder structure, it has the correct folders and files. No idea why it failed.

Promise rejected with value: [ { name: 'app', value: 'app' },
  { name: 'app/home', value: 'home' } ]
Promise rejected with value: [ { name: 'app', value: 'app' },
  { name: 'app/home', value: 'home' } ]
TypeError: Cannot read property 'replace' of undefined
    at writing$ (/usr/local/lib/node_modules/generator-ng-poly/generators/directive/index.js:38:52)
    at tryCatch (/usr/local/lib/node_modules/generator-ng-poly/node_modules/babel-polyfill/node_modules/babel-regenerator-runtime/runtime.js:61:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/generator-ng-poly/node_modules/babel-polyfill/node_modules/babel-regenerator-runtime/runtime.js:329:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/generator-ng-poly/node_modules/babel-polyfill/node_modules/babel-regenerator-runtime/runtime.js:94:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/generator-ng-poly/node_modules/babel-polyfill/node_modules/babel-regenerator-runtime/runtime.js:136:37)
    at run (/usr/local/lib/node_modules/generator-ng-poly/node_modules/babel-polyfill/node_modules/core-js/modules/es6.promise.js:89:22)
    at /usr/local/lib/node_modules/generator-ng-poly/node_modules/babel-polyfill/node_modules/core-js/modules/es6.promise.js:102:28
    at flush (/usr/local/lib/node_modules/generator-ng-poly/node_modules/babel-polyfill/node_modules/core-js/modules/_microtask.js:18:9)
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)
TypeError: Cannot read property 'replace' of undefined
    at writing$ (/usr/local/lib/node_modules/generator-ng-poly/generators/directive/index.js:38:52)
    at tryCatch (/usr/local/lib/node_modules/generator-ng-poly/node_modules/babel-polyfill/node_modules/babel-regenerator-runtime/runtime.js:61:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/generator-ng-poly/node_modules/babel-polyfill/node_modules/babel-regenerator-runtime/runtime.js:329:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/generator-ng-poly/node_modules/babel-polyfill/node_modules/babel-regenerator-runtime/runtime.js:94:21)
    at GeneratorFunctionPrototype.invoke (/usr/local/lib/node_modules/generator-ng-poly/node_modules/babel-polyfill/node_modules/babel-regenerator-runtime/runtime.js:136:37)
    at run (/usr/local/lib/node_modules/generator-ng-poly/node_modules/babel-polyfill/node_modules/core-js/modules/es6.promise.js:89:22)
    at /usr/local/lib/node_modules/generator-ng-poly/node_modules/babel-polyfill/node_modules/core-js/modules/es6.promise.js:102:28
    at flush (/usr/local/lib/node_modules/generator-ng-poly/node_modules/babel-polyfill/node_modules/core-js/modules/_microtask.js:18:9)
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)

**Comment by dustinspecker** [comment]
Really sorry about that! It's fixed now. It'll be released in a few minutes after CI finishes.
