### ISSUE TITLE
TypeError: Path must be a string. Received null

### ISSUE THREAD

**Issue by phipex** [dustinspecker/generator-ng-poly#322]
fail in creation of module, service, controller, etc. 

$ node -v
v4.3.0

$ npm -v
3.8.0

$ yo --version
1.8.3

$ yo ng-poly:view newView --module=home/kitchen                                                                                                                                                    
TypeError: Path must be a string. Received null                                                                                                                                                    
    at assertPath (path.js:8:11)                                                                                                                                                                   
    at Object.win32.join (path.js:221:5)                                                                                                                                                           
    at _callee$ (C:\Users\sony vaio\AppData\Roaming\npm\node_modules\generator-ng-poly\generators\utils\app.js:35:42)                                                                              
    at tryCatch (C:\Users\sony vaio\AppData\Roaming\npm\node_modules\generator-ng-poly\node_modules\babel-regenerator-runtime\runtime.js:61:40)                                                    
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\sony vaio\AppData\Roaming\npm\node_modules\generator-ng-poly\node_modules\babel-regenerator-runtime\runtime.js:329:22)             
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\Users\sony vaio\AppData\Roaming\npm\node_modules\generator-ng-poly\node_modules\babel-regenerator-runtime\runtime.js
:94:21)                                                                                                                                                                                            
    at GeneratorFunctionPrototype.invoke (C:\Users\sony vaio\AppData\Roaming\npm\node_modules\generator-ng-poly\node_modules\babel-regenerator-runtime\runtime.js:136:37)                          
    at run (C:\Users\sony vaio\AppData\Roaming\npm\node_modules\generator-ng-poly\node_modules\core-js\modules\es6.promise.js:89:22)                                                               
    at C:\Users\sony vaio\AppData\Roaming\npm\node_modules\generator-ng-poly\node_modules\core-js\modules\es6.promise.js:102:28                                                                    
    at flush (C:\Users\sony vaio\AppData\Roaming\npm\node_modules\generator-ng-poly\node_modules\core-js\modules\_microtask.js:18:9)                                                               
TypeError: Path must be a string. Received null                                                                                                                                                    
    at assertPath (path.js:8:11)                                                                                                                                                                   
    at Object.win32.join (path.js:221:5)                                                                                                                                                           
    at _callee$ (C:\Users\sony vaio\AppData\Roaming\npm\node_modules\generator-ng-poly\generators\utils\app.js:35:42)                                                                              
    at tryCatch (C:\Users\sony vaio\AppData\Roaming\npm\node_modules\generator-ng-poly\node_modules\babel-regenerator-runtime\runtime.js:61:40)                                                    
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\sony vaio\AppData\Roaming\npm\node_modules\generator-ng-poly\node_modules\babel-regenerator-runtime\runtime.js:329:22)             
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\Users\sony vaio\AppData\Roaming\npm\node_modules\generator-ng-poly\node_modules\babel-regenerator-runtime\runtime.js
:94:21)                                                                                                                                                                                            
    at GeneratorFunctionPrototype.invoke (C:\Users\sony vaio\AppData\Roaming\npm\node_modules\generator-ng-poly\node_modules\babel-regenerator-runtime\runtime.js:136:37)                          
    at run (C:\Users\sony vaio\AppData\Roaming\npm\node_modules\generator-ng-poly\node_modules\core-js\modules\es6.promise.js:89:22)                                                               
    at C:\Users\sony vaio\AppData\Roaming\npm\node_modules\generator-ng-poly\node_modules\core-js\modules\es6.promise.js:102:28                                                                    
    at flush (C:\Users\sony vaio\AppData\Roaming\npm\node_modules\generator-ng-poly\node_modules\core-js\modules\_microtask.js:18:9)

**Comment by dustinspecker** [comment]
Are you using the latest version of `ng-poly`? I believe `v0.12.4` fixes this problem. Sorry for the inconvenience.

**Comment by phipex** [comment]
my version is generator-ng-poly@0.12.4, i updated this today, try uninstall and install, thanks

**Comment by dustinspecker** [comment]
Hmm. I'm having trouble reproducing this.

Is this an existing project or a brand new project? If existing, do you know what version of ng-poly was used to initially scaffold it? By default, that version is in the `readme.md`.

**Comment by phipex** [comment]
the proyect is new, the version is same,i resolved unistall and reinstall, i created a new project so run succeful any commans, maybe display this error because i´m not update the generator last year or i updated from yeoman interface, but reinstall it fix the problem, thanks
