### ISSUE TITLE
Maximum Call Stack

### ISSUE THREAD

**Issue by jack10** [dustinspecker/generator-ng-poly#93]
Hey guys i got a huge problem. I set up a ne ng-poly project and cant build it. Is there anything I can do about it?
```
[20:41:31] 'bowerCopy' errored after 3.21 s
[20:41:31] Error: RangeError: Maximum call stack size exceeded
  at formatError (/usr/lib/node_modules/gulp/bin/gulp.js:169:10)
  at Gulp.<anonymous> (/usr/lib/node_modules/gulp/bin/gulp.js:195:15)
  at Gulp.emit (events.js:95:17)
  at Gulp.Orchestrator._emitTaskDone (/home/jakub/polymer-test/node_modules/gulp/node_modules/orchestrator/index.js:264:8)
  at /home/jakub/polymer-test/node_modules/gulp/node_modules/orchestrator/index.js:275:23
  at finish (/home/jakub/polymer-test/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:21:8)
  at module.exports (/home/jakub/polymer-test/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:36:10)
  at Gulp.Orchestrator._runTask (/home/jakub/polymer-test/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
  at Gulp.Orchestrator._runStep (/home/jakub/polymer-test/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
  at /home/jakub/polymer-test/node_modules/gulp/node_modules/orchestrator/index.js:279:18
  at finish (/home/jakub/polymer-test/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:21:8)
  at /home/jakub/polymer-test/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:52:4
  at f (/home/jakub/polymer-test/node_modules/gulp/node_modules/orchestrator/node_modules/end-of-stream/node_modules/once/once.js:17:25)
  at DestroyableTransform.onend (/home/jakub/polymer-test/node_modules/gulp/node_modules/orchestrator/node_modules/end-of-stream/index.js:31:18)
  at DestroyableTransform.emit (events.js:117:20)
  at /home/jakub/polymer-test/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:965:16
  at process._tickCallback (node.js:442:13)
```
my bower.json is kind of minimal

```
{                                                                                                                                       
  "name": "polymer-test",
  "version": "0.0.0",
  "dependencies": {
    "angular": "~1.3.*",
    "angular-touch": "~1.3.*",
    "angular-ui-router": "~0.2.10",
    "font-awesome": "~4.2.0",
    "polymer": "Polymer/polymer#~0.5.0",
    "core-elements": "Polymer/core-elements#~0.5.0",
    "paper-elements": "Polymer/paper-elements#~0.5.0",
    "restangular": "~1.4.0"
  },  
  "devDependencies": {
    "angular-mocks": "~1.3.*"
  }
}
```

**Comment by jack10** [comment]
even if I run gulp like this 
```
node --stack-size=5000 /usr/lib/node_modules/gulp/bin/gulp.js
```
with 10000 I get 
```
 terminated by signal SIGSEGV (Address boundary error)
```

**Comment by dustinspecker** [comment]
Hmmm. This seems to be a Mac OS X issue (https://github.com/wearefractal/vinyl-fs/issues/14#issuecomment-45668095)

Just for a sanity check:
Change the gulp/test.js bowerCopy task from
```javascript
...
return stream.done()
    .pipe(cssFilter)
    .pipe($.if(isProd, $.concat('vendor.css')))
    .pipe($.if(isProd, $.cssmin()))
    ...
```

to

```javascript
...
return stream.done()
    .on('data', function (file) {
      console.log(file.path);
    })
    .pipe(cssFilter)
    .pipe($.if(isProd, $.concat('vendor.css')))
    .pipe($.if(isProd, $.cssmin()))
    ...
```

What's the output of that? The default project with the options you selected should output 6 files.
```
angular.js
angular-touch.js
angular-ui-router.js
lodash.compat.js
restangular.js
font-awesome.css

**Comment by jack10** [comment]
Well I did some checks and added some printlines where it fails

My complete boweCopy
```javascript
// copy bower components into build directory
gulp.task('bowerCopy', ['inject'], function () {
  console.log("init css filter");
  var cssFilter = $.filter('**/*.css')
  console.log("init js filter");
  var jsFilter = $.filter('**/*.js')

  console.log("init stream");
  var stream = $.streamqueue({objectMode: true})
  console.log("init wiredep");                                                                                                                                                                                                                                                   
  var wiredep = $.wiredep({exclude: [/polymer/, /webcomponents/]});

  console.log("running js wiredep");
  if (wiredep.js) {
    stream.queue(gulp.src(wiredep.js));
  }

  console.log("running css wiredep");
  if (wiredep.css) {
    stream.queue(gulp.src(wiredep.css));
  }

  console.log("going to strea.done");
  return stream.done()
    .on('data', function (file) {
      console.log(file.path);
    })  
    .pipe(cssFilter)
    .pipe($.if(isProd, $.concat('vendor.css')))
    .pipe($.if(isProd, $.cssmin()))
    .pipe($.if(isProd, $.rev()))
    .pipe(gulp.dest(buildConfig.extCss))
    .pipe(cssFilter.restore())
    .pipe(jsFilter)
    .pipe($.if(isProd, $.concat('vendor.js')))
    .pipe($.if(isProd, $.uglify({
      preserveComments: $.uglifySaveLicense
    })))
    .pipe($.if(isProd, $.rev()))
    .pipe(gulp.dest(buildConfig.extJs))
    .pipe(jsFilter.restore());
});
```
output of this

```
[20:38:41] Using gulpfile ~/polymer-test/Gulpfile.js
[20:38:41] Starting 'clean'...
[20:38:41] Starting 'lint'...
[20:38:45] Starting 'staticAnalysis'...
[20:38:45] Finished 'clean' after 4.39 s
[20:38:45] Starting 'markup'...
[20:38:46] Starting 'styles'...
[20:38:47] Starting 'images'...
[20:38:49] Starting 'fontsBower'...
[20:38:49] Finished 'images' after 2.09 s
[20:38:50] Finished 'lint' after 9.05 s
[20:38:50] Finished 'staticAnalysis' after 5.07 s
[20:38:50] Starting 'analyze'...
[20:38:50] Finished 'analyze' after 46 μs
[20:38:50] Finished 'styles' after 4.07 s
[20:38:50] Finished 'markup' after 4.67 s
[20:38:50] Starting 'scripts'...
[20:38:51] Finished 'scripts' after 1.44 s
[20:38:51] Starting 'inject'...
[20:38:52] Finished 'fontsBower' after 2.3 s
[20:38:52] Starting 'fonts'...
[20:38:52] Finished 'fonts' after 4.03 ms
[20:38:52] gulp-inject 6 files into index.html.
[20:38:52] gulp-inject 1 files into index.html.
[20:38:52] Finished 'inject' after 279 ms
[20:38:52] Starting 'bowerCopy'...
init css filter
init js filter
init stream
init wiredep
[20:38:55] 'bowerCopy' errored after 3.26 s
[20:38:55] Error: RangeError: Maximum call stack size exceeded
  at formatError (/usr/lib/node_modules/gulp/bin/gulp.js:169:10)
  at Gulp.<anonymous> (/usr/lib/node_modules/gulp/bin/gulp.js:195:15)
  at Gulp.emit (events.js:95:17)
  at Gulp.Orchestrator._emitTaskDone (/home/jakub/polymer-test/node_modules/gulp/node_modules/orchestrator/index.js:264:8)
  at /home/jakub/polymer-test/node_modules/gulp/node_modules/orchestrator/index.js:275:23
  at finish (/home/jakub/polymer-test/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:21:8)
  at module.exports (/home/jakub/polymer-test/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:36:10)
  at Gulp.Orchestrator._runTask (/home/jakub/polymer-test/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
  at Gulp.Orchestrator._runStep (/home/jakub/polymer-test/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
  at /home/jakub/polymer-test/node_modules/gulp/node_modules/orchestrator/index.js:279:18
  at finish (/home/jakub/polymer-test/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:21:8)
  at /home/jakub/polymer-test/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:52:4
  at f (/home/jakub/polymer-test/node_modules/gulp/node_modules/orchestrator/node_modules/end-of-stream/node_modules/once/once.js:17:25)
  at DestroyableTransform.onend (/home/jakub/polymer-test/node_modules/gulp/node_modules/orchestrator/node_modules/end-of-stream/index.js:31:18)
  at DestroyableTransform.emit (events.js:117:20)
  at /home/jakub/polymer-test/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:965:16
  at process._tickCallback (node.js:442:13)
```

**Comment by dustinspecker** [comment]
That's odd. Can you try scaffolding out a project without Polymer enabled? If that project works we might just need to be sure to exclude the paper and core items - there are a lot of them.

**Comment by jack10** [comment]
Well the thing is I'm on linux (archlinux) so it's not a Mac problem. But without polymer it works ;)

**Comment by dustinspecker** [comment]
Oh, sweet. That I can get access to. I'll play around with this today or tomorrow and see if we can figure this out.

**Comment by jack10** [comment]
I also did some test. 

if i run wiredep like documented, on a test html file `wiredep -s test.html` i get this.
```html
<html>
  <head>
      <!-- bower:css -->
      <link rel="stylesheet" href="bower_components/font-awesome/css/font-awesome.css" />
      <!-- endbower -->
  </head>
  <body>
      <!-- bower:js -->
      <script src="bower_components/angular/angular.js"></script>
      <script src="bower_components/angular-touch/angular-touch.js"></script>
      <script src="bower_components/angular-ui-router/release/angular-ui-router.js"></script>
      <script src="bower_components/webcomponentsjs/webcomponents.js"></script>
      <script src="bower_components/polymer/polymer.js"></script>
      <script src="bower_components/lodash/dist/lodash.compat.js"></script>
      <script src="bower_components/restangular/dist/restangular.js"></script>
      <!-- endbower -->
  </body>
</html>
```
So I though maybe it helps to remove the excludes from wiredep in `gulp/build.js` i get some more output ;)

```
[16:57:51] Using gulpfile ~/polymer-test/Gulpfile.js
[16:57:51] Starting 'clean'...
[16:57:51] Starting 'lint'...
[16:57:55] Starting 'staticAnalysis'...
[16:57:55] Finished 'clean' after 4.38 s
[16:57:55] Starting 'markup'...
[16:57:56] Starting 'styles'...
[16:57:58] Starting 'images'...
[16:57:59] Starting 'fontsBower'...
[16:58:00] Finished 'images' after 2 s
[16:58:00] Finished 'lint' after 8.82 s
[16:58:00] Finished 'staticAnalysis' after 4.84 s
[16:58:00] Starting 'analyze'...
[16:58:00] Finished 'analyze' after 16 μs
[16:58:00] Finished 'styles' after 3.9 s
[16:58:00] Finished 'markup' after 4.45 s
[16:58:00] Starting 'scripts'...
[16:58:01] Finished 'scripts' after 1.35 s
[16:58:01] Starting 'inject'...
[16:58:02] Finished 'fontsBower' after 2.15 s
[16:58:02] Starting 'fonts'...
[16:58:02] Finished 'fonts' after 5.78 ms
[16:58:02] gulp-inject 6 files into index.html.
[16:58:02] gulp-inject 1 files into index.html.
[16:58:02] Finished 'inject' after 244 ms
[16:58:02] Starting 'bowerCopy'...
init css filter
init js filter
init stream
init wiredep
running js wiredep
running css wiredep
going to strea.done
/home/jakub/polymer-test/bower_components/angular/angular.js
/home/jakub/polymer-test/bower_components/angular-touch/angular-touch.js
/home/jakub/polymer-test/bower_components/angular-ui-router/release/angular-ui-router.js
/home/jakub/polymer-test/bower_components/webcomponentsjs/webcomponents.js
/home/jakub/polymer-test/bower_components/polymer/polymer.js
/home/jakub/polymer-test/bower_components/lodash/dist/lodash.compat.js
/home/jakub/polymer-test/bower_components/restangular/dist/restangular.js
/home/jakub/polymer-test/bower_components/font-awesome/css/font-awesome.css
[16:58:02] Finished 'bowerCopy' after 346 ms
[16:58:02] Starting 'bowerInject'...

events.js:72
        throw er; // Unhandled 'error' event
              ^
RangeError: Maximum call stack size exceeded
```
Maybe this helps ^^

**Comment by dustinspecker** [comment]
I think #147 has a fix.
